name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Check Format
        run: yarn test:format

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Lint
        run: yarn test:lint

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn workspace client build

  build-axon-docker:
    name: Build Axon Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Axon Docker Image
        run: docker build -t wpilib/axon:latest .
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon.latest.tar wpilib/axon:latest
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: wpilib_axon.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon:latest

  build-ml-base-docker:
    name: Build ML Base Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ML Base Image
        run: docker build -t wpilib/axon-base:latest .
        working-directory: ./packages/ml/mobilenet/base
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_base.latest.tar wpilib/axon-base:latest
        working-directory: ./packages/ml/mobilenet/base
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/base/wpilib_axon_base.latest.tar
      - name: Publish Docker Image
#        if: |
#          github.repository_owner == 'wpilibsuite' &&
#          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-base:latest

  build-ml-dataset-docker:
    name: Build ML Dataset Container
    runs-on: ubuntu-latest
    needs: build-ml-base-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build ML Dataset Image
        run: docker build -t wpilib/axon-dataset:latest .
        working-directory: ./packages/ml/mobilenet/dataset
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_dataset.latest.tar wpilib/axon-dataset:latest
        working-directory: ./packages/ml/mobilenet/dataset
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/dataset/wpilib_axon_dataset.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-dataset:latest

  build-ml-metrics-docker:
    name: Build ML Metrics Container
    runs-on: ubuntu-latest
    needs: build-ml-base-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build ML Metrics Image
        run: docker build -t wpilib/axon-metrics:latest .
        working-directory: ./packages/ml/mobilenet/metrics
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_metrics.latest.tar wpilib/axon-metrics:latest
        working-directory: ./packages/ml/mobilenet/metrics
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/metrics/wpilib_axon_metrics.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-metrics:latest

  build-ml-test-docker:
    name: Build ML Test Container
    runs-on: ubuntu-latest
    needs: build-ml-base-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build ML Test Image
        run: docker build -t wpilib/axon-test:latest .
        working-directory: ./packages/ml/mobilenet/test
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_test.latest.tar wpilib/axon-test:latest
        working-directory: ./packages/ml/mobilenet/test
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/test/wpilib_axon_test.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-test:latest

  build-ml-tflite-docker:
    name: Build ML TFLite Container
    runs-on: ubuntu-latest
    needs: build-ml-base-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build ML TFLite Image
        run: docker build -t wpilib/axon-tflite:latest .
        working-directory: ./packages/ml/mobilenet/tflite
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_tflite.latest.tar wpilib/axon-tflite:latest
        working-directory: ./packages/ml/mobilenet/tflite
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/tflite/wpilib_axon_tflite.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-tflite:latest

  build-ml-training-docker:
    name: Build ML Training Container
    runs-on: ubuntu-latest
    needs: build-ml-base-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build ML Training Image
        run: docker build -t wpilib/axon-training:latest .
        working-directory: ./packages/ml/mobilenet/training
      - name: Save Axon Docker Image
        run: docker save -o wpilib_axon_training.latest.tar wpilib/axon-training:latest
        working-directory: ./packages/ml/mobilenet/training
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: ./packages/ml/mobilenet/training/wpilib_axon_training.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wpilib/axon-training:latest
