name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Check Format
        run: yarn test:format

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Lint
        run: yarn test:lint

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn workspace client build

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t wpilib/axon:latest .
      - name: Save Docker Image
        run: docker save -o wpilib_axon.latest.tar wpilib/axon:latest
      - uses: actions/upload-artifact@v2
        with:
          name: Docker Container
          path: wpilib_axon.latest.tar
      - name: Publish Docker Image
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: docker push wpilib/axon:latest
